chapter 4/objective 3/TestWebApp/Models/BankAccount.cs
namespace TestWebApp.Models
{
    public class BankAccount
    {
        private static int _ids = 1;

        private readonly string _owner;
        private readonly int _id;

        public BankAccount(string owner)
            : this(owner, 0)
        {
        }

        public BankAccount(string owner, decimal initialBalance)
        {
            _id = _ids++;

            Balance = initialBalance;
            _owner = owner;
        }

        public decimal Balance { get; set; }

        public int Id => _id;

        public string Owner => _owner;
    }
}

chapter 4/objective 3/TestWebApp/Controllers/BankAccountController.cs
using System.Web.Mvc;
using TestWebApp.Services;

namespace TestWebApp.Controllers
{
    public class BankAccountController : Controller
    {
        private readonly BankAccountService _bankAccountService;

        public BankAccountController()
        {
            _bankAccountService = new BankAccountService();
        }

        // GET: BankAccount
        public ActionResult Index()
        {
            var accounts = _bankAccountService.GetAccounts();
            return View(accounts);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string owner)
        {
            _bankAccountService.CreateAccount(owner);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var account = _bankAccountService.GetAccount(id);
            return View(account);
        }

        public ActionResult Details(int id)
        {
            var account = _bankAccountService.GetAccount(id);
            return View(account);
        }

        [HttpPost]
        public void Debit(int id, decimal amount)
        {
            _bankAccountService.Debit(id, amount);
        }

        [HttpPost]
        public void Deposit(int id, decimal amount)
        {
            _bankAccountService.Deposit(id, amount);
        }
    }
}

chapter 4/objective 3/TestWebApp/Controllers/HomeController.cs
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult About()
        {
            ViewBag.Message = "Exam ref Unit test examples";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "My contact page.";

            return View();
        }
    }
}

chapter 4/objective 3/TestWebApp/Views/BankAccount/Create.cshtml
@model TestWebApp.Models.BankAccount

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BankAccount</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Owner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Owner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

chapter 4/objective 3/TestWebApp/Views/BankAccount/Details.cshtml
@model TestWebApp.Models.BankAccount

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

chapter 4/objective 3/TestWebApp/Views/BankAccount/Edit.cshtml
@model TestWebApp.Models.BankAccount

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="form-horizontal">
    <h4>BankAccount</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Owner, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Amount</label>
        <div class="col-md-10">
            <input id="amount" type="text" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button id="debit" class="btn btn-default">Debit</button>
            <button id="deposit" class="btn btn-default">Deposit</button>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

            $("#debit")
                .click(function () {
                    var id = $('input#Id').val();
                    var amount = $('input#amount').val();

                    $.ajax({
                        url: "@Url.Action("Debit")",
                        data: { 'id': id, 'amount': amount },
                        type: "post",
                        cache: false,
                        success: function () {
                            var url = "@Url.Action("Details", new {id = "__id__"})";
                            window.location.href = url.replace('__id__', id);
                        }
                    });
                });

            $("#deposit")
                .click(function () {
                    var id = $('input#Id').val();
                    var amount = $('input#amount').val();

                    $.ajax({
                        url: "@Url.Action("Deposit")",
                        data: { 'id': id, 'amount': amount },
                        type: "post",
                        cache: false,
                        success: function () {
                            var url = "@Url.Action("Details", new {id = "__id__"})";
                            window.location.href = url.replace('__id__', id);
                        }
                    });
                });
        });
    </script>
}

chapter 4/objective 3/TestWebApp/Views/BankAccount/Index.cshtml
@model IEnumerable<TestWebApp.Models.BankAccount>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Owner)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Balance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
            </td>
        </tr>
    }
</table>

chapter 4/objective 3/TestWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

chapter 4/objective 3/TestWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Bessenveldstraat 19<br />
    1831 Diegem<br />
    <abbr title="Phone">P:</abbr>
    02/708.11.11
</address>

chapter 4/objective 3/TestWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My TestWebApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TestWebApp", "Index", "BankAccount", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "BankAccount")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My TestWebApp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>